USE [Teste]
GO
IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_VALORES') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_NOTA_FISCAL_ITEM_VALORES
    IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_VALORES') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_NOTA_FISCAL_ITEM_VALORES >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_ITEM_VALORES APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE P_NOTA_FISCAL_ITEM_VALORES
AS
BEGIN
	select 
	 Cfop as CFOP, 
	 SUM(BaseIcms) as TotalBaseICMS, SUM(ValorIcms) as ValorICMS, 
	 SUM(BaseIPI) as TotalIPI, SUM(ValorIPI) as ValorIPI
	from dbo.NotaFiscalItem
	group by Cfop 
END
GO
GRANT EXECUTE ON dbo.P_NOTA_FISCAL_ITEM_VALORES TO [public]
go
IF OBJECT_ID('dbo.P_NOTA_FISCAL_ITEM_VALORES') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_ITEM_VALORES CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_NOTA_FISCAL_ITEM_VALORES >>>'
go