USE [Teste]
GO
IF OBJECT_ID('dbo.P_NOTA_FISCAL_CFOP_VALORES') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_NOTA_FISCAL_CFOP_VALORES
    IF OBJECT_ID('dbo.P_NOTA_FISCAL_CFOP_VALORES') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_NOTA_FISCAL_CFOP_VALORES >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_CFOP_VALORES APAGADA >>>'
END
go
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON 
GO 
CREATE PROCEDURE P_NOTA_FISCAL_CFOP_VALORES
AS
BEGIN
	select 
	 Id,
	 EstadoOrigem,
	 EstadoDestino,
	 ValorCFOP
	from dbo.NotaFiscalCFOP
END
GO
GRANT EXECUTE ON dbo.P_NOTA_FISCAL_CFOP_VALORES TO [public]
go
IF OBJECT_ID('dbo.P_NOTA_FISCAL_CFOP_VALORES') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_NOTA_FISCAL_CFOP_VALORES CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_NOTA_FISCAL_CFOP_VALORES >>>'
go